### ISSUE TITLE
What is the different between phpLDAPadmin?

### ISSUE THREAD

**Issue by KomaBeyond** [operasoftware/ssh-key-authority#1]
Just like what i said in the title. This is useful.

**Comment by thomasp-opera** [comment]
They serve very different purposes. phpLDAPadmin is for administering an LDAP directory server. ssh-key-authority is for managing SSH authorized key files on remote servers.

Perhaps viewing the [ssh-key-authority demo site](https://ska.xiven.com/) would help your understanding.

Use one of the following sets of username / password credentials to log in:

* testuser / testuser - normal user with admin access granted to a few servers
* testadmin / testadmin - admin user

All data on this demonstration server is reset nightly at 00:00 UTC.
