### ISSUE TITLE
Unable to setup on ubuntu 

### ISSUE THREAD

**Issue by imranbaigOps** [operasoftware/ssh-key-authority#12]
error : [Mon May 14 14:52:32.475389 2018] [php7:notice] [pid 13349] [client 10.72.5.188:57221] 1526295152: Exception: Not logged in. in /var/www/ssh-key-authority/requesthandler.php:26\n1526295152: Stack trace:\n1526295152: #0 /var/www/ssh-key-authority/public_html/init.php(18): require()\n1526295152: #1 {main}, referer: http://10.72.4.155/

I have followed the Read.ME still it fails to load the tool.

![image](https://user-images.githubusercontent.com/25133298/39993408-cf2b6b54-5786-11e8-9e3e-891bda45d996.png)

@thomas-pike please advise

**Comment by thomas-pike** [comment]
Have you set up some form of authentication on the Apache web server? We have some [example configurations for our DNS UI tool](https://github.com/operasoftware/dns-ui/wiki#example-configurations) which are also reasonably applicable to SSH Key Authority.

**Comment by imranbaigOps** [comment]
Thanks @thomas-pike  for your prompt reply really appreciated, 

Now I have enabled the Authentication I get prompt to enter credentials . However still says Something went wrong.
error : [Mon May 14 16:02:23.876384 2018] [php7:notice] [pid 2827] [client 10.72.5.195:54181] 1526299343: ErrorException: ldap_search(): Search: Can't contact LDAP server in /var/www/ssh-key-authority/ldap.php:48\n1526299343: Stack trace:\n1526299343: #0 [internal function]: exception_error_handler(2, 'ldap_search(): ...', '/var/www/ssh-ke...', 48, Array)\n1526299343: #1 /var/www/ssh-key-authority/ldap.php(48): ldap_search(Resource id #3, 'ou=users,dc=exa...', 'uid=admin', Array)\n1526299343: #2 /var/www/ssh-key-authority/model/user.php(311): LDAP->search('ou=users,dc=exa...', 'uid=admin', Array)\n1526299343: #3 /var/www/ssh-key-authority/model/userdirectory.php(99): User->get_details_from_ldap()\n1526299343: #4 /var/www/ssh-key-authority/requesthandler.php(24): UserDirectory->get_user_by_uid('admin')\n1526299343: #5 /var/www/ssh-key-authority/public_html/init.php(18): require('/var/www/ssh-ke...')\n1526299343: #6 {main}, referer: http://10.72.4.155/

**Comment by thomas-pike** [comment]
Looks like the LDAP setup in config/config.ini is incorrect. For example, `dn_user` looks like it is still set to `ou=users,dc=example,dc=com`.
