### ISSUE TITLE
AD Integration

### ISSUE THREAD

**Issue by Kwiescent** [operasoftware/ssh-key-authority#14]
Hello.
I am trying to integrate ska with AD.
config.ini [ldap] section
`host = ldap://xxx.xxx.xxx.xxx:389`
`starttls = 0`
`dn_user = "ou=users,dc=corp,dc=domain,dc=tld"`
`dn_group = "ou=rolebasedgroups,dc=corp,dc=domain,dc=tld"`
`bind_dn = ska@corp.domain.tld`
`bind_password = SomeStrongPass`
`user_id = samAccountName`
`user_name = cn`
`user_email = mail`
`group_member = memberOf`
`group_member_value = samAccountName`
`admin_group_cn = ska-administrators`
After logon I am having an error, see screenshot.
![error_screen](https://user-images.githubusercontent.com/40855374/42317153-09b940dc-8065-11e8-9231-24bef9de5b3d.jpg)
Apache error log
`[:error] [pid 12036] [client yyy.yyy.yyy.yyy:13708] 1530782564: exception 'ErrorException' with message 'ldap_bind(): Unable to bind to server: Invalid credentials' in /opt/ska/ldap.php:41\n1530782564: Stack trace:\n1530782564: #0 [internal function]: exception_error_handler(2, 'ldap_bind(): Un...', '/opt/ska/ldap.p...', 41, Array)\n1530782564: #1 /opt/ska/ldap.php(41): ldap_bind(Resource id #23, 'ska@corp.domain....', '2')\n1530782564: #2 /opt/ska/ldap.php(46): LDAP->connect()\n1530782564: #3 /opt/ska/model/user.php(311): LDAP->search('ou=users,dc=domain...', 'samAccountName=...', Array)\n1530782564: #4 /opt/ska/model/userdirectory.php(99): User->get_details_from_ldap()\n1530782564: #5 /opt/ska/requesthandler.php(24): UserDirectory->get_user_by_uid('logged_on_user')\n1530782564: #6 /opt/ska/public_html/init.php(18): require('/opt/ska/reques...')\n1530782564: #7 {main}`
Meanwhile I can connect with bind_dn and bind_password to AD host from ADExplorer successfully.
What should I do to fix this?
Thanks.

**Comment by thomas-pike** [comment]
Hi

This error is generated by PHP's `ldap_bind()` function which is reporting that the credentials you've provided are not being accepted by the server. As such it is hard for me to tell you what exactly is wrong, but I might be able to point you in the right direction for figuring it out.

The [top comment on the ldap_bind PHP manual page](http://php.net/manual/en/function.ldap-bind.php#103034) is about debugging issues binding with Active Directory. I would suggest that you take the PHP code from their comment, put it into a `test.php` file with the correct LDAP server and login details and try running it from the command line (eg. `php test.php`). Hopefully this might get you a more useful error message.

**Comment by Kwiescent** [comment]
Thanks for the reply.
I modified a little this diagnostic script.
`<?php`
`$ldaphost = "xxx.xxx.xxx.xxx";`
`$ldapport = 389;`
`$bind_dn = "ska@corp.domain.tld";`
`$bind_password = "SomeStrongPass";`
` `
`define(LDAP_OPT_DIAGNOSTIC_MESSAGE, 0x0032);`
`$handle = ldap_connect($ldaphost, $ldapport);`
`echo "$handle\n";`
`if ($handle) {`
 `ldap_set_option($handle, LDAP_OPT_PROTOCOL_VERSION, 3);`
 `ldap_set_option($handle, LDAP_OPT_REFERRALS, 0);`
 `$bind = ldap_bind($handle, $bind_dn, $bind_password);`
 `echo "$bind\n";`
 `ldap_get_option($handle, LDAP_OPT_DIAGNOSTIC_MESSAGE, $extended_error);`
 `echo "$extended_error\n";`
`}`
`?>`
First run:
`Resource id #4`
`1`
` `
Then I checked Reset User Passwords and Force Password Change at Next Logon in AD for ska user
Second run:
`Resource id #4`
`PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /root/ad_bind_test.php on line 14`
` `
`80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 773, v2580`
Then I unchecked Reset User Passwords and Force Password Change at Next Logon and set Account has expired to 02.07.18.
3rd run:
`Resource id #4`
`PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /root/ad_bind_test.php on line 14`
` `
`80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 701, v2580`
If I change $bind_dn to ska (without domain part after at) then I get error Invalid credentials too
4th run:
`Resource id #4`
`PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /root/ad_bind_test.php on line 14`
` `
`80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580`
All of these tries mean that binding should be successfull, as I use settings in config.ini from 1st run.

**Comment by Kwiescent** [comment]
After escaping bind_dn and bind_password error Invalid credentials disappears.

**Comment by Kwiescent** [comment]
Now I have ldap_search error)

**Comment by thomas-pike** [comment]
Looks like you had success? You needed to escape some special characters in the `bind_dn` and `bind_password`?

**Comment by Kwiescent** [comment]
Sorry, term misuse. Actually I told about quoting not escaping.
Like this: 
`bind_dn = 'ska@corp.domain.tld'`
`bind_password = 'SomeStrongPass'`

**Comment by thomas-pike** [comment]
Right, it might be wise then for me to quote these values in `config-sample.ini` so that others are less likely to encounter this problem.
