### ISSUE TITLE
Adding servers.

### ISSUE THREAD

**Issue by Kwiescent** [operasoftware/ssh-key-authority#15]
Hello.
Another stupid question: how to add servers to ska?
On Servers tab I see only Filter options not Add button for example.
Thanks.

**Comment by thomas-pike** [comment]
I'm afraid this comes back to LDAP configuration again then: somehow ska is not detecting you as being in the group, whether the group information is not visible to the account you are binding to, or if one of the configuration values is wrong I can't be sure.

I would very much like to see a successful AD integration, so please let me know if you can figure it out.

After adjusting the configuration you can run `scripts/ldap_update.php` to update all the accounts.

**Comment by Kwiescent** [comment]
I should not have changed default values group_member and group_member_value.
This:
`group_member = member`
`group_member_value = dn`
works perfect.
