### ISSUE TITLE
sync status still pending on web

### ISSUE THREAD

**Issue by mattdika** [operasoftware/ssh-key-authority#23]
Please help, after update hostname on database, sync status on web still "pending" , but after sync manual with command, user can be access the server but on the web sync_status still pending.

need your help.

![image](https://user-images.githubusercontent.com/43978964/46646007-f2535e80-cbb1-11e8-8bad-b6528ca52a41.png)
![image](https://user-images.githubusercontent.com/43978964/46646028-04350180-cbb2-11e8-93fa-a5ed89776bfb.png)

**Comment by thomas-pike** [comment]
Is the `keys-sync` daemon enabled and running? eg. see `systemctl status keys-sync.service` or `service keys-sync status`

**Comment by mattdika** [comment]
Hi thomas,

it's running normally and enabled
![image](https://user-images.githubusercontent.com/43978964/46662361-72df8280-cbe5-11e8-98ad-cbffc9da1a9f.png)

if i sync with script, and it finished and success, but still pending on the web of KMS
![image](https://user-images.githubusercontent.com/43978964/46662507-ceaa0b80-cbe5-11e8-9272-933103f20992.png)

why "sync_status" still pending ?

**Comment by mattdika** [comment]
Hi @thomas-pike ,

Thanks it solved the problem, the keys-sync.service is not running on my server, after keys-sync.service started "pending" on sync_status has gone.
