### ISSUE TITLE
An inactive user can log in and see the list of servers, keys etc

### ISSUE THREAD

**Issue by Simonell** [operasoftware/ssh-key-authority#3]
An inactive user can log in and see the list of servers, keys etc.

**Comment by thomasp-opera** [comment]
It is currently expected that you configure the restriction of inactive users in your Apache virtual host configuration, eg:

AuthLDAPURL ldaps://ldap.example.com/dc=example,dc=com?uid?sub?(!(organizationalStatus=FORMER))

**Comment by thomasp-opera** [comment]
But that said, it would not be difficult to add such a check in the application too.
