### ISSUE TITLE
Better UX

### ISSUE THREAD

**Issue by Stunic** [operasoftware/ssh-key-authority#30]
Hi,

first of all I love the tool. But one thing isnt really User Friendly.
It would be great if a user wouldn't even have the chance to click on the root account of a server.

![image](https://user-images.githubusercontent.com/42865014/51391504-867a7d80-1b32-11e9-99b3-b7cee42b3e1e.png)

![image](https://user-images.githubusercontent.com/42865014/51391534-9eea9800-1b32-11e9-91e4-bf6c52094e90.png)

Could you add that when its a root account the links are removed and the "Manage Account" button are disabled?

So the Users doesnt have to see the "Ooops! Something went wrong!" so often.

**Comment by thomas-pike** [comment]
The error page you see is definitely a bug, and not expected behaviour. Please see if the last commit I did fixes this for you.

**Comment by Stunic** [comment]
that fixed it! Thank you!
