### ISSUE TITLE
External Pub-Keys

### ISSUE THREAD

**Issue by Stunic** [operasoftware/ssh-key-authority#31]
I have an ftp server with many local users for external clients with no access to my Active Directory.

Is there a way to assign a public key to a local serveraccount?

I thought the public keys tab in the serveraccount could be used for this, but as it said its only for outgoing connections not for the incoming connections i need.

My workaround is to set up the server with only the root account an then manually add the users public key in /var/local/keys-sync/[username]. Which works but defeats the purpose of a ssh-key-authority.

**Comment by thomas-pike** [comment]
The way we would typically do this was to create a "dummy" server (set to not be managed by SKA), add an account on it, give it the relevant public keys, and then grant that account access to the actual server, using a server-to-server access rule.

**Comment by Stunic** [comment]
Thanks for the fast response! It worked!
