### ISSUE TITLE
Centos 8 wrong permissions

### ISSUE THREAD

**Issue by antonzhelyazkov** [operasoftware/ssh-key-authority#46]
Hi Opera Team,

SKA is brilliant software. I use it for several months and works great.
I have issue with Centos 8 installations. When I add new key all key file permissions changes to 0600 and no one can login except root. For example:

 ```
ll /var/local/keys-sync/
total 16
-rw------- 1 keys-sync keys-sync 1658 May 11 22:22 user2
-rw-r--r-- 1 root      root      1414 May 11 22:21 keys-sync
-rw------- 1 keys-sync keys-sync 2338 May 11 22:22 user1
-rw------- 1 keys-sync keys-sync  292 May 11 22:22 root
```

Could you help me to deal with this issue?

**Comment by thomas-pike** [comment]
Hi

I'm not as familiar with Centos as I am with Debian/Ubuntu, but I would check what `umask` settings you have for the keys-sync user and for the system in general. That is what would typically cause a file to be created with lower permissions that intended. It looks like you might have a `umask` of `0077` here perhaps.
