### ISSUE TITLE
Problem with SQL Injection

### ISSUE THREAD

**Issue by wastez** [operasoftware/ssh-key-authority#53]
Hello,

I´ve the following problem:
`PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system = ?' at line 1 in /srv/keys/model/groupdirectory.php:35
Stack trace:
#0 /srv/keys/model/groupdirectory.php(35): mysqli->prepare()
#1 /srv/keys/scripts/ldap_update.php(44): GroupDirectory->add_group()
#2 {main}
  thrown in /srv/keys/model/groupdirectory.php on line 35`

Seems `group` isn't escaped correctly.
But i`m not good in php, so can you please help me?

Thanks.

**Comment by thomas-pike** [comment]
This would appear to indicate that `system` has become a reserved word in MySQL, perhaps a change in recent MySQL versions. If that is truly the case, then the fix would be to change this line:
```
$stmt = $this->database->prepare("INSERT INTO `group` SET entity_id = ?, name = ?, system = ?");
```
to this:
```
$stmt = $this->database->prepare("INSERT INTO `group` SET entity_id = ?, name = ?, `system` = ?");
```
Could you try this and see if it helps?
