### ISSUE TITLE
Multiple hosts behind NAT

### ISSUE THREAD

**Issue by wastez** [operasoftware/ssh-key-authority#57]
Hello,

I've at least one problem.
We have a few hosts behind a nat which are accessable with the same ip but with different ports.
Would it be possible to have a "behind NAT" tick so that the ip check will allow it?

**Comment by thomas-pike** [comment]
I don't any infrastructure to test this with, but as far as I can tell it should be working. Have you definitely done a `git pull` to update to the latest version, and then restarted the sync process? Can you check the output from the sync process when you run a sync? `journalctl -f -u keys-sync` should show what it is doing. Take a look for lines that mention `Checking IP address`.

**Comment by wastez** [comment]
Hello,

I tested a little bit.
This isnt working:
$matching_servers = $server_dir->list_servers(array(), array('ip_address' => $server->ip_address, 'port' => $server->port, 'key_management' => array('keys')));


We have 4 amachines with different IPs, but also different Ports
I echo'ed the count($matchingservers).
And the result is still 4.

**Comment by thomas-pike** [comment]
Ah, I see where I went wrong. I'll have a fix shortly.

**Comment by thomas-pike** [comment]
I believe this should work now. I also put the fix on to the `sync_groups` branch in case you are testing that.

**Comment by wastez** [comment]
Perfect, this is working now.

But i will test the other thing with the groups not on our life system.

Will inform you!

Thanks for your work.

**Comment by thomas-pike** [comment]
Excellent. Thanks for your help debugging it.
