### ISSUE TITLE
Add ability to change application root?

### ISSUE THREAD

**Issue by figless** [operasoftware/ssh-key-authority#6]
Hello,
I really like this project, but for our use case we require to have the app running from something other than /
For example: example.com/authentication/ssh is a reverse proxy that would forward to backend.local/authentication/ssh

Is it possible to add support to change the app to respond on a user configurable application root such as /authentication/ssh?

**Comment by thomasp-opera** [comment]
True, there are certainly cases where it would be useful to change the application root URL. In theory it's not a difficult change to make (a modification in either requesthandler.php or router.php would make the path be handled correctly by the application), but currently there are a lot of links all throughout the application that are all hardcoded to the root path, and these will of course need fixing.
