### ISSUE TITLE
Add LDAP user_filter and group_filter config settings

### ISSUE THREAD

**Issue by thomas-pike** [operasoftware/ssh-key-authority#60]
If users and groups are in the same subtree in LDAP, very confusing things can happen (eg. lines 44-52 of `views/server.php` will find a "user" that is actually a group when trying to add a group as an admin of a server).

If we add some optional `user_query` and `group_query` attributes to filter them separately then we can avoid this problem and support a greater variety of LDAP structures.

**Comment by thomas-pike** [comment]
Perhaps user_filter and group_filter would be better names.

**Comment by thomas-pike** [comment]
`group_filter` isn't actually needed, since we never directly fetch groups (instead fetching them from the user's `group_member` attribute).

**Comment by thomas-pike** [comment]
> `group_filter` isn't actually needed, since we never directly fetch groups (instead fetching them from the user's `group_member` attribute).

This is not entirely true. Although we do fetch based on the member attribute, we do still fetch from groups. While it shouldn't be necessary, it would be good to add it for safety anyway.

**Comment by wastez** [comment]
Now i get everywhere access denied.

**Comment by wastez** [comment]
Forget it. Sorry.

**Comment by wastez** [comment]
Ok, i get everywhere access denied right now if a user filter is set.

**Comment by thomas-pike** [comment]
Is your user filter correct? If it doesn't match any users that would be likely to cause all users to be deactivated.

**Comment by wastez** [comment]
Ok with user_filter = "(objectClass=user)" it is working.

**Comment by wastez** [comment]
Tank you very much ;)

**Comment by wastez** [comment]
And the other problem at first login?

**Comment by thomas-pike** [comment]
Ok, glad we finally got that sorted :) Now just to fix that last bug...

**Comment by wastez** [comment]
Really great, thanks for spending your time.
