### ISSUE TITLE
Non-standard SSH ports

### ISSUE THREAD

**Issue by matt-horwood-mayden** [operasoftware/ssh-key-authority#8]
Good evening,

I have been looking at this project as it would be a good fit for me to deploy at work, but we use non-standard SSH ports on all our servers. I cant see how I can add the port to a server.

Could you ether advise if I can or if I should add code?

**Comment by thomas-pike** [comment]
Hi

This is not currently supported, but it shouldn't be too hard for us to add.

**Comment by matt-horwood-mayden** [comment]
Hi @thomas-pike 
that would be good if you could, as we have a very big mess of servers that we need some way to tidy up.

**Comment by thomas-pike** [comment]
Not quite resolved yet, forgot the most important part of the change...

**Comment by matt-horwood-mayden** [comment]
hi @thomas-pike 

looks like will be a good fit once its finished, thanks for fix
